### ISSUE TITLE
welciaのチラシ取得時にphantomjsがエラー

### ISSUE THREAD

**Issue by mollinaca** [mollinaca/flyers#1]
```
[Exception]
Message: Service /usr/local/bin/phantomjs unexpectedly exited. Status code was: 127

[StackTrace]
Traceback (most recent call last):
  File "/mnt/extDisk/sho/workspace/flyers/flyers/__main__.py", line 132, in main
    pics = welcia.get_flyers_pics (p)
  File "/mnt/extDisk/sho/workspace/flyers/flyers/welcia/welcia.py", line 62, in get_flyers_pics
    driver = webdriver.PhantomJS(executable_path='/usr/local/bin/phantomjs', service_log_path=os.path.devnull)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/phantomjs unexpectedly exited. Status code was: 127
```
welciaの処理でphantomjsがエラー
たぶん、ページをパースした結果、リンクや何らかのデータの取得に失敗（決め打ちしてる部分）して、nullで再度取得するような流れでエラーとかそういう感じだと思うので処理を追って調査する

**Comment by mollinaca** [comment]
いったん該当部分を pass させる
https://github.com/mollinaca/flyers/commit/8afef9bbfed1ea62a0436fafbddb7751f40cb8b1

**Comment by mollinaca** [comment]
追加でエラー
```
[Exception]
'NoneType' object has no attribute 'get_text'
[StackTrace]
Traceback (most recent call last):
  File "/mnt/d/tools/workspace/development/flyers/flyers/__main__.py", line 143, in main
    pics = welcia.get_flyers_pics (p)
  File "/mnt/d/tools/workspace/development/flyers/flyers/welcia/welcia.py", line 77, in get_flyers_pics
    n = int(html.find('div', {'class':'cv_pager_number'}).get_text().split('/')[1].strip())
AttributeError: 'NoneType' object has no attribute 'get_text'
```
