### ISSUE TITLE
業務スーパーのチラシ取得時のエラー

### ISSUE THREAD

**Issue by mollinaca** [mollinaca/flyers#4]
スクレイピングのエラー
```
[StackTrace]
Traceback (most recent call last):
  File "/mnt/d/tools/workspace/development/flyers/flyers/__main__.py", line 97, in main
    gs_flyers = gyomusuper.get_flyers()
  File "/mnt/d/tools/workspace/development/flyers/flyers/gyomusuper/gyomusuper.py", line 15, in get_flyers
    leaflet_page_url = tokubai_url + html.findAll(class_='leaflet_component')[0].find(class_='image_element').get('href')
IndexError: list index out of range
```
確認する

**Comment by mollinaca** [comment]
いったん業務スーパーの取得を停止する
