### ISSUE TITLE
chromedriver error

### ISSUE THREAD

**Issue by mollinaca** [mollinaca/flyers#8]
cron実行において
```
[Exception]
Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[StackTrace]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/extDisk/sho/workspace/flyers/flyers/__main__.py", line 141, in main
    pics = welcia.get_flyers_pics (p)
  File "/mnt/extDisk/sho/workspace/flyers/flyers/welcia/welcia.py", line 69, in get_flyers_pics
    driver = webdriver.Chrome (options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
おそらくPipenvがactivateできていない

**Comment by mollinaca** [comment]
とりあえずウエルシアをまたとめておく・・・

**Comment by mollinaca** [comment]
see also: https://github.com/mollinaca/chromedriver-test/issues/1

**Comment by mollinaca** [comment]
```
Subject: Cron <sho@chromebook1>    cd "${SCRIPT_DIR}"; source /home/sho/.local/share/virtualenvs/flyers-OhApUgB6/bin/activate; /usr/bin/python3 -m flyers >/dev/null 2>&1
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SCRIPT_DIR=/home/sho/workspace/flyers>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/sho>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=sho>
Message-Id: <20210624100020.D078A374@chromebook1>
Date: Thu, 24 Jun 2021 19:00:20 +0900 (JST)

/bin/sh: 1: source: not found
```

source コマンドが実行できないのか・・・

**Comment by mollinaca** [comment]
参考になりそうなもの
https://qiita.com/munaita_/items/4cf39d154239e02f4c9b
https://base64.work/so/python/1902255
https://stackoverflow.com/questions/48990067/how-to-run-a-cron-job-with-pipenv
